parameters:

services:
  _defaults:
    autowire: true      # Automatyczne wstrzykiwanie zależności
    autoconfigure: true # Automatyczne przypisanie tagów (np. dla event subscriberów)

  Aflorczak\CommunityBundle\:
    resource: ../src/  
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Controller/'
      - '../src/Services/'
