services:
  Aflorczak\CommunityBundle\Services\MyFirstServiceInCommunityBundle: null
  Aflorczak\CommunityBundle\Controller\HomeController:
    resource:
      '../src/Controller/'
    tags:
      ['controller.service_arguments']